<?php

namespace App\Langs\levels\Phrases;

use App\Langs\BaseLevel;

/**
 * Created by PhpStorm.
 * User: Roman Pytka
 * Date: 2/28/21
 * Time: 8:23 AM
 */

class PhrasesB2 extends BaseLevel
{
    public $title = 'czasowniki frazowe B2';
    public $desc = '';
    public $slug = 'phrasal-verbs-b2';
    public $data = [
        'sth' => [
           
            ["break down", "zepsuć się", "My car broke down on the way to work.", "Mój samochód zepsuł się w drodze do pracy."],
            ["come across", "natknąć się", "I came across an old friend at the mall.", "Natknąłem się na starego przyjaciela w centrum handlowym."],
            ["give up", "poddać się", "She gave up smoking last year.", "Ona rzuciła palenie w zeszłym roku."],
            ["look after", "opiekować się", "Can you look after my dog while I'm on vacation?", "Czy możesz zaopiekować się moim psem kiedy będę na wakacjach?"],
            ["run out of", "skończyć się", "We've run out of milk.", "Skończyło nam się mleko."],
            ["take off", "wystartować", "The plane took off at 7 PM.", "Samolot wystartował o 19:00."],
            ["put off", "przełożyć", "They put off the meeting until next week.", "Przełożyli spotkanie na przyszły tydzień."],
            ["set up", "założyć", "She set up her own company last year.", "Ona założyła swoją firmę w zeszłym roku."],
            ["turn down", "odrzucić", "He turned down the job offer.", "Odrzucił ofertę pracy."],
            ["work out", "rozwiązać, wypracować", "We need to work out the details before signing the contract.", "Musimy wypracować szczegóły przed podpisaniem umowy."],
            ["bring up", "wspomnieć", "She didn't bring up the issue during the meeting.", "Nie wspomniała o problemie podczas spotkania."],
            ["call off", "odwołać", "They called off the event due to the weather.", "Odwołali wydarzenie z powodu pogody."],
            ["get along with", "dogadywać się", "I get along with my colleagues very well.", "Bardzo dobrze dogaduję się z moimi kolegami z pracy."],
            ["hold on", "czekać", "Can you hold on for a moment?", "Czy możesz chwilę poczekać?"],
            ["look forward to", "oczekiwać z niecierpliwością", "I'm looking forward to the weekend.", "Nie mogę się doczekać weekendu."],
            ["make up", "wymyślać", "He made up an excuse for being late.", "Wymyślił wymówkę za spóźnienie."],
            ["pick up", "odebrać", "I'll pick you up at 7 PM.", "Odbiorę cię o 19:00."],
            ["show up", "pojawić się", "He didn't show up to the meeting.", "Nie pojawił się na spotkaniu."],
            ["turn up", "pojawić się", "She turned up late for the party.", "Pojawiła się spóźniona na imprezie."],
            ["figure out", "rozgryźć", "I need to figure out how to fix this.", "Muszę rozgryźć, jak to naprawić."],
            ["check out", "sprawdzić", "Check out this new software; it's really useful.", "Sprawdź to nowe oprogramowanie; jest naprawdę przydatne."],
            ["carry on", "kontynuować", "She carried on with her work despite the noise.", "Kontynuowała swoją pracę pomimo hałasu."],
            ["bring about", "spowodować", "The new law brought about significant changes.", "Nowe prawo spowodowało znaczące zmiany."],
            ["give in", "poddać się", "After hours of negotiation, he finally gave in.", "Po godzinach negocjacji w końcu się poddał."],
            ["get over", "dojść do siebie", "It took me a while to get over the flu.", "Zajęło mi trochę czasu, aby dojść do siebie po grypie."],
            ["go on", "kontynuować", "Please go on with your story.", "Proszę kontynuuj swoją opowieść."],
            ["look into", "zbadać", "The police are looking into the case.", "Policja bada sprawę."],
            ["put up with", "znosić, tolerować", "I can't put up with his behavior anymore.", "Nie mogę już dłużej znosić jego zachowania."],
            ["turn on", "włączyć", "Can you turn on the lights?", "Czy możesz włączyć światła?"],
            ["turn off", "wyłączyć", "Please turn off your phone during the meeting.", "Proszę wyłącz telefon podczas spotkania."],
            ["take up", "zająć się czymś", "I've recently taken up painting.", "Ostatnio zacząłem zajmować się malarstwem."],
            

            ["back up", "wycofać się, wspierać", "She decided to back up her friend in the argument.", "Postanowiła wesprzeć swoją przyjaciółkę w kłótni."],
            ["break in", "włamać się", "Someone tried to break in last night.", "Ktoś próbował się włamać zeszłej nocy."],
            ["bring out", "wydobyć, uwydatnić", "The new dress really brings out her eyes.", "Nowa sukienka naprawdę podkreśla jej oczy."],
            ["call in", "wezwać", "We had to call in a specialist to fix the problem.", "Musieliśmy wezwać specjalistę, aby rozwiązać problem."],
            ["catch up with", "dogonić, nadrobić", "I need to catch up with my work.", "Muszę nadrobić zaległości w pracy."],
            ["come up with", "wymyślić, zaproponować", "He came up with a brilliant idea.", "Wpadł na genialny pomysł."],
            ["cut down on", "ograniczyć", "I need to cut down on sugar.", "Muszę ograniczyć spożycie cukru."],
            ["do away with", "pozbyć się", "We should do away with old traditions.", "Powinniśmy pozbyć się starych tradycji."],
            ["drop out", "rzucić (np. szkołę)", "He dropped out of college in his second year.", "Rzucił studia na drugim roku."],
            ["end up", "skończyć (gdzieś, jako coś)", "He ended up working in a completely different field.", "Skończył pracując w zupełnie innej branży."],
            ["fall apart", "rozpaść się", "Their marriage fell apart after five years.", "Ich małżeństwo rozpadło się po pięciu latach."],
            ["fall behind", "zalegać, mieć zaległości", "I've fallen behind with my homework.", "Mam zaległości w pracy domowej."],
            ["find out", "dowiedzieć się", "I found out that she was moving to another city.", "Dowiedziałem się że przeprowadza się do innego miasta."],
            ["get along", "dogadywać się", "We get along well despite our differences.", "Dogadujemy się dobrze mimo naszych różnic."],
            ["get away with", "ujść na sucho", "He got away with cheating on the test.", "Uszło mu na sucho oszukiwanie na teście."],
            ["get by", "przetrwać, radzić sobie", "I can get by with my current salary.", "Radzę sobie z moją obecną pensją."],
            ["get in", "wejść, wsiąść", "He got in the car and drove away.", "Wsiadł do samochodu i odjechał."],
            ["give out", "rozdawać", "They were giving out free samples at the store.", "Rozdawali darmowe próbki w sklepie."],
            ["go ahead", "kontynuować, śmiało", "You can go ahead and start without me.", "Możesz śmiało zacząć beze mnie."],
            ["go over", "przejrzeć, omówić", "Let's go over the details one more time.", "Przejrzyjmy szczegóły jeszcze raz."],
            ["grow up", "dorastać", "I grew up in a small town.", "Dorastałem w małym miasteczku."],
            ["hang out", "spędzać czas, przebywać", "We usually hang out at the park on weekends.", "Zwykle spędzamy czas w parku w weekendy."],
            ["keep up with", "nadążać za", "It's hard to keep up with all the latest news.", "Trudno nadążyć za wszystkimi najnowszymi wiadomościami."],
            ["let down", "zawieść kogoś", "He let me down when he didn't show up.", "Zawiódł mnie, kiedy się nie pojawił."],
            ["look out", "uważać", "Look out for cars when crossing the street.", "Uważaj na samochody, przechodząc przez ulicę."],
            ["make up for", "nadrobić, zrekompensować", "I'll make up for missing your party.", "Zrekompensuję ci to że nie przyszedłem na twoją imprezę."],
            ["pass away", "odejść, umrzeć", "His grandfather passed away last year.", "Jego dziadek zmarł w zeszłym roku."],
            ["pick out", "wybrać", "She picked out a nice dress for the party.", "Wybrała ładną sukienkę na imprezę."],
            ["point out", "wskazać", "He pointed out an error in my report.", "Wskazał na błąd w moim raporcie."],
            ["put on", "założyć, ubrać", "He put on his coat before leaving.", "Założył płaszcz przed wyjściem."],
            ["put out", "zgasić", "The firefighters quickly put out the fire.", "Strażacy szybko ugasili ogień."],
            ["set off", "wyruszyć, rozpocząć", "We set off on our journey at dawn.", "Wyruszyliśmy w podróż o świcie."],
            ["show off", "popisywać się", "He likes to show off his new car.", "Lubi popisywać się swoim nowym samochodem."],
            ["slow down", "zwolnić", "You should slow down when driving in the rain.", "Powinieneś zwolnić jadąc w deszczu."],
            ["stand out", "wyróżniać się", "Her bright red dress made her stand out in the crowd.", "Jej jaskrawoczerwona sukienka wyróżniała ją w tłumie."],
            ["take after", "być podobnym do", "She takes after her mother in many ways.", "Jest podobna do swojej matki w wielu aspektach."],
            ["take back", "zwrócić, cofnąć", "I take back what I said about you.", "Cofam to, co powiedziałem o tobie."],
            ["take over", "przejąć kontrolę", "He took over the family business.", "Przejął kontrolę nad rodzinnym biznesem."],
            ["talk into", "namówić", "He talked me into going to the party.", "Namówił mnie na pójście na imprezę."],
            ["talk out of", "odwieść kogoś od czegoś", "I tried to talk him out of quitting his job.", "Próbowałem go odwieść od rzucenia pracy."],
            ["tear down", "zburzyć, zdemolować", "They're going to tear down the old building.", "Zamierzają zburzyć stary budynek."],
            ["think over", "przemyśleć", "I'll think it over and give you an answer tomorrow.", "Przemyślę to i dam ci odpowiedź jutro."],
            ["throw away", "wyrzucić", "Don't throw away that old chair; it's an antique.", "Nie wyrzucaj tego starego krzesła; to antyk."],
            ["turn around", "odwrócić się", "She turned around when she heard her name.", "Odwróciła się, kiedy usłyszała swoje imię."],
            ["turn up", "pojawić się", "The missing cat turned up after two days.", "Zaginiony kot pojawił się po dwóch dniach."],
            ["use up", "zużyć", "We've used up all the milk.", "Zużyliśmy całe mleko."],
            ["wake up", "obudzić się", "I woke up early this morning.", "Obudziłem się wcześnie rano."],
            ["wash up", "umyć się", "Don't forget to wash up before dinner.", "Nie zapomnij się umyć przed kolacją."],
            ["watch out", "uważać", "Watch out for the dog; it bites.", "Uważaj na psa; gryzie."],
            ["work out", "ćwiczyć, trenować", "I work out every morning.", "Ćwiczę każdego ranka."],
            ["write down", "zapisać", "Write down the address so you don't forget it.", "Zapisz adres żeby go nie zapomnieć."],
            ["run into", "wpaść na kogoś", "I ran into an old friend at the store.", "Wpadłem na starego znajomego w sklepie."],
            ["run out of", "skończyć się", "We've run out of coffee.", "Skończyła nam się kawa."],
            ["see off", "pożegnać", "We went to the airport to see him off.", "Poszliśmy na lotnisko żeby się z nim pożegnać."],
            ["set up", "ustawić, założyć", "They set up a new company last year.", "Założyli nową firmę w zeszłym roku."],
            ["show up", "pojawić się", "He didn't show up for the meeting.", "Nie pojawił się na spotkaniu."],
            ["sort out", "rozwiązać, uporządkować", "We need to sort out this mess.", "Musimy rozwiązać ten bałagan."],
            ["take off", "wystartować", "The plane took off on time.", "Samolot wystartował o czasie."],
            ["talk over", "omówić", "Let's talk it over before making a decision.", "Omówmy to przed podjęciem decyzji."],
            ["throw up", "wymiotować", "He threw up after eating bad seafood.", "Zwrócił jedzenie po zjedzeniu zepsutych owoców morza."],
            ["turn in", "oddać (np. pracę, raport)", "I have to turn in my essay by tomorrow.", "Muszę oddać moją pracę do jutra."],
            ["turn into", "zamienić się w", "The caterpillar turned into a butterfly.", "Gąsienica zamieniła się w motyla."],
            ["wake up to", "uświadomić sobie coś", "She woke up to the reality of the situation.", "Uświadomiła sobie realia sytuacji."],
            ["walk out on", "zostawić, porzucić", "He walked out on his family.", "Zostawił swoją rodzinę."],
            ["work on", "pracować nad czymś", "I'm working on a new project.", "Pracuję nad nowym projektem."],
            ["work up", "wypracować", "She worked up the courage to speak in public.", "Wypracowała odwagę, aby przemawiać publicznie."],
            ["wrap up", "zakończyć, zapakować", "Let's wrap up the meeting.", "Zakończmy spotkanie."],
        
            ["account for", "wyjaśnić, stanowić", "This explains why the expenses account for most of the budget.", "To wyjaśnia, dlaczego wydatki stanowią większość budżetu."],
            ["act up", "źle się zachowywać, sprawiać problemy", "My computer is acting up again.", "Mój komputer znowu sprawia problemy."],
            ["ask around", "pytać wśród ludzi", "I asked around to find a good mechanic.", "Pytałem wśród ludzi, aby znaleźć dobrego mechanika."],
            ["back down", "ustąpić", "She refused to back down in the argument.", "Odmówiła ustąpienia w kłótni."],
            ["back out", "wycofać się", "He backed out of the deal at the last minute.", "Wycofał się z umowy w ostatniej chwili."],
            ["bear with", "być cierpliwym wobec kogoś", "Please bear with me while I find the information.", "Proszę o cierpliwość, podczas gdy szukam informacji."],
            ["blow up", "wysadzić, wybuchnąć", "The bomb blew up in the middle of the city.", "Bomba wybuchła w centrum miasta."],
            ["break away", "oderwać się, uciec", "The dog broke away from its owner.", "Pies oderwał się od właściciela."],
            ["break down", "zepsuć się, załamać się", "My car broke down on the way to work.", "Mój samochód zepsuł się w drodze do pracy."],
            ["break into", "włamać się", "Thieves broke into the house last night.", "Złodzieje włamali się do domu wczoraj w nocy."],
            ["bring about", "doprowadzić do, spowodować", "The new policy brought about significant changes.", "Nowa polityka doprowadziła do znaczących zmian."],
            ["bring down", "obniżyć, zmniejszyć", "The government is trying to bring down inflation.", "Rząd próbuje obniżyć inflację."],
            ["bring forward", "przesunąć na wcześniejszy termin", "The meeting has been brought forward to Monday.", "Spotkanie zostało przesunięte na poniedziałek."],
            ["bring up", "wychowywać, poruszyć temat", "She brought up an interesting point during the discussion.", "Poruszyła interesującą kwestię podczas dyskusji."],
            ["call off", "odwołać", "The match was called off due to rain.", "Mecz został odwołany z powodu deszczu."],
            ["carry on", "kontynuować", "Please carry on with your work.", "Proszę kontynuować swoją pracę."],
            ["carry out", "przeprowadzić, wykonać", "The scientists carried out an experiment.", "Naukowcy przeprowadzili eksperyment."],
            ["catch on", "zyskać na popularności", "The new song quickly caught on.", "Nowa piosenka szybko zyskała na popularności."],
            ["catch up on", "nadrabiać zaległości", "I need to catch up on my reading.", "Muszę nadrobić zaległości w czytaniu."],
            ["chip in", "zrzucić się, dorzucić się", "We all chipped in for the gift.", "Wszyscy zrzuciliśmy się na prezent."],
            ["come across", "napotkać, natknąć się", "I came across an old friend in the market.", "Natknąłem się na starego znajomego na rynku."],
            ["come down with", "zachorować na", "He came down with the flu last week.", "Zachorował na grypę w zeszłym tygodniu."],
            ["come forward", "zgłosić się, wyjść z inicjatywą", "Several witnesses came forward with new evidence.", "Kilku świadków zgłosiło się z nowymi dowodami."],
            ["come into", "odziedziczyć", "She came into a large sum of money.", "Odziedziczyła dużą sumę pieniędzy."],
            ["come over", "wpaść (z wizytą)", "Why don't you come over for dinner?", "Może wpadniesz na kolację?"],
            ["come up", "pojawić się, wyniknąć", "Something has come up at work.", "Coś się pojawiło w pracy."],
            ["come up against", "natknąć się na trudności", "We came up against a lot of opposition.", "Natknęliśmy się na dużą opozycję."],
            ["count on", "liczyć na kogoś", "You can count on me to help.", "Możesz na mnie liczyć."],
            ["cut back", "ograniczać", "We've had to cut back on our spending.", "Musieliśmy ograniczyć nasze wydatki."],
            ["cut off", "odciąć, przerwać", "The phone line was cut off.", "Linia telefoniczna została odcięta."],
            ["deal with", "radzić sobie z czymś", "She has to deal with a lot of stress at work.", "Musi radzić sobie z dużym stresem w pracy."],
            ["do up", "odnawiać, zapinać", "They are doing up the house.", "Odnawiają dom."],
            ["drag on", "ciągnąć się, przedłużać", "The meeting dragged on for hours.", "Spotkanie ciągnęło się godzinami."],
            ["drop by", "wpaść z wizytą", "Feel free to drop by anytime.", "Wpadnij w dowolnym momencie."],
            ["drop off", "odpaść, zmniejszyć się, zasnąć", "Business has dropped off recently.", "Biznes ostatnio się zmniejszył."],
            ["drop out of", "rzucić, zrezygnować z", "He dropped out of school when he was 16.", "Rzucił szkołę, gdy miał 16 lat."],
            ["ease off", "zmniejszać się, zelżeć", "The rain is finally easing off.", "Deszcz wreszcie słabnie."],
            ["end up with", "skończyć z czymś", "He ended up with more money than he started with.", "Skończył z większą ilością pieniędzy niż zaczął."],
            ["fall for", "dać się nabrać, zakochać się", "He fell for her the moment he saw her.", "Zakochał się w niej, gdy tylko ją zobaczył."],
            ["fall out with", "pokłócić się z kimś", "She fell out with her best friend.", "Pokłóciła się ze swoją najlepszą przyjaciółką."],
            ["figure out", "zrozumieć, rozwiązać", "I finally figured out how to solve the problem.", "W końcu zrozumiałem, jak rozwiązać problem."],
            ["fill in", "wypełnić, uzupełnić", "Please fill in this form.", "Proszę wypełnić ten formularz."],
            ["find out about", "dowiedzieć się o czymś", "I found out about the new job opportunity.", "Dowiedziałem się o nowej możliwości pracy."],
            ["get around", "przemieszczać się", "It's easy to get around the city by bus.", "Łatwo przemieszczać się po mieście autobusem."],
            ["get back at", "odegrać się, zemścić się", "He's trying to get back at her for the insult.", "Próbuje się na niej odegrać za obrazę."],
            ["get down to", "zabrać się za coś", "Let's get down to business.", "Zabierzmy się do pracy."],
            ["get off", "wysiąść, zejść", "We got off the bus at the wrong stop.", "Wysiedliśmy z autobusu na złym przystanku."],
            ["get over", "przeboleć, dojść do siebie", "It took her a long time to get over the breakup.", "Zajęło jej dużo czasu, aby dojść do siebie po rozstaniu."],
            ["get through", "przetrwać, dodzwonić się", "I finally got through to the customer service.", "W końcu dodzwoniłem się do obsługi klienta."],
            ["give in", "poddawać się", "He finally gave in to their demands.", "W końcu poddał się ich żądaniom."],
            ["give off", "wydzielać", "The flowers give off a wonderful fragrance.", "Kwiaty wydzielają cudowny zapach."],
            ["give up on", "rezygnować z czegoś, stracić nadzieję", "Don't give up on your dreams.", "Nie rezygnuj ze swoich marzeń."],
            ["go after", "dążyć do czegoś, gonić za czymś", "He went after his dream of becoming an actor.", "Dążył do swojego marzenia aby zostać aktorem."],
            ["go ahead with", "kontynuować, zaczynać", "They decided to go ahead with the plan.", "Zdecydowali się kontynuować plan."],
            ["go along with", "zgodzić się, akceptować", "I went along with her suggestion.", "Zgodziłem się z jej sugestią."],
            ["go by", "przechodzić obok, upływać", "Time goes by so quickly.", "Czas tak szybko mija."],
            ["go off", "zepsuć się, wybuchnąć", "The alarm went off at 6 a.m.", "Alarm wyłączył się o 6 rano."],
            ["go over", "przejrzeć, powtórzyć", "Let's go over the details one more time.", "Przejrzyjmy jeszcze raz szczegóły."],
            ["go through with", "zrealizować coś mimo trudności", "He went through with the project despite the challenges.", "Zrealizował projekt pomimo trudności."],
            ["grow apart", "oddalać się od siebie", "They've grown apart over the years.", "Oni oddalili się od siebie przez lata."],
            ["hand down", "przekazać coś młodszemu pokoleniu", "This necklace was handed down from my grandmother.", "Ten naszyjnik został przekazany od mojej babci."],
            ["hand in", "oddać coś (np. pracę domową)", "Please hand in your assignments by Friday.", "Proszę oddać zadania do piątku."],
            ["hand out", "rozdawać", "The teacher handed out the exam papers.", "Nauczyciel rozdał arkusze egzaminacyjne."],
            ["hang around", "kręcić się, pałętać", "We used to hang around the park after school.", "Zwykle kręciliśmy się po parku po szkole."],
            ["hang on", "czekać chwilę, trzymać się", "Hang on, I'll be with you in a moment.", "Poczekaj chwilę, zaraz będę."],
            ["hold back", "powstrzymać, wstrzymać", "She couldn't hold back her tears.", "Nie mogła powstrzymać łez."],
            ["hold on to", "trzymać się czegoś", "Hold on to the railing for support.", "Trzymaj się poręczy dla wsparcia."],
            ["keep away", "trzymać się z daleka", "Keep away from the edge of the cliff.", "Trzymaj się z dala od krawędzi klifu."],
            ["keep on", "kontynuować", "He kept on working despite the noise.", "Kontynuował pracę pomimo hałasu."],
            ["kick off", "rozpocząć (np. spotkanie)", "The meeting will kick off at 10 a.m.", "Spotkanie rozpocznie się o 10 rano."],
            ["leave out", "pominąć, opuścić", "You can leave out this part of the report.", "Możesz pominąć tę część raportu."],
            ["let down", "zawieść kogoś", "He felt let down by his friends.", "Czuł się zawiedziony przez swoich przyjaciół."],
            ["live up to", "sprostać oczekiwaniom", "He tried to live up to his parents' expectations.", "Starał się sprostać oczekiwaniom swoich rodziców."],
            ["look after", "opiekować się", "She looks after her younger brother.", "Opiekuje się młodszym bratem."],
            ["look back on", "wspominać", "I often look back on our time together.", "Często wspominam nasz wspólny czas."],
            ["look forward to", "oczekiwać z niecierpliwością", "I'm looking forward to the weekend.", "Nie mogę się doczekać weekendu."],
            ["look out for", "wypatrywać, uważać na", "Look out for traffic when crossing the street.", "Uważaj na ruch drogowy podczas przechodzenia przez ulicę."],
            ["look up to", "podziwiać kogoś", "I've always looked up to my older brother.", "Zawsze podziwiałem mojego starszego brata."],
            ["make up for", "nadrobić, zrekompensować", "She tried to make up for her mistake.", "Starała się nadrobić swój błąd."],
            ["mess around", "wygłupiać się, marnować czas", "Stop messing around and get to work.", "Przestań się wygłupiać i weź się do pracy."],
            ["pass out", "zemdleć", "He passed out from the heat.", "Zemdlał z powodu upału."],
            ["pay off", "opłacać się, spłacić", "All the hard work finally paid off.", "Cała ciężka praca w końcu się opłaciła."],
            ["pick on", "czepiać się kogoś, dokuczać", "They always pick on the new kid.", "Zawsze czepiają się nowego dziecka."],
            ["point out", "wskazać, zwrócić uwagę", "She pointed out a mistake in the report.", "Wskazała błąd w raporcie."],
            ["pull off", "osiągnąć coś trudnego, udać się", "He managed to pull off a difficult project.", "Udało mu się zrealizować trudny projekt."],
            ["put off", "odłożyć na później", "Let's put off the meeting until next week.", "Przełóżmy spotkanie na przyszły tydzień."],
            ["put up with", "znosić, tolerować", "I can't put up with this noise any longer.", "Nie mogę dłużej znosić tego hałasu."],
            ["run into", "natknąć się na kogoś", "I ran into an old friend at the store.", "Natknąłem się na starego przyjaciela w sklepie."],
            ["run out of", "skończyć się, wyczerpać", "We've run out of milk.", "Skończyło nam się mleko."],
            ["see through", "przejrzeć kogoś", "I can see through his lies.", "Przejrzałem jego kłamstwa."],
            ["set off", "wyruszyć w podróż", "We set off early in the morning.", "Wyruszyliśmy wcześnie rano."],
            ["settle down", "ustatkować się, osiedlić się", "They decided to settle down in a small town.", "Postanowili osiedlić się w małym miasteczku."],
            ["show off", "popisywać się", "He likes to show off his new car.", "Lubi popisywać się swoim nowym samochodem."],
            ["sleep in", "spać dłużej niż zwykle", "I like to sleep in on weekends.", "Lubię spać dłużej w weekendy."],
            ["stand by", "wspierać kogoś, być w gotowości", "I'll stand by you no matter what.", "Będę cię wspierać, bez względu na wszystko."],
            ["stand out", "wyróżniać się", "She really stands out in a crowd.", "Naprawdę wyróżnia się w tłumie."],
            ["step down", "ustąpić ze stanowiska", "He decided to step down as CEO.", "Postanowił ustąpić ze stanowiska dyrektora generalnego."],
            ["stick to", "trzymać się czegoś", "Let's stick to the original plan.", "Trzymajmy się pierwotnego planu."],
            ["take in", "przyjąć, zrozumieć", "It was a lot of information to take in.", "To była duża ilość informacji do przyswojenia."],
            ["talk into", "namówić kogoś do czegoś", "She talked me into going to the party.", "Namówiła mnie do pójścia na imprezę."],
            ["tear down", "zburzyć, rozebrać", "They plan to tear down the old building.", "Planują zburzyć stary budynek."],
            ["tell off", "zbesztać, skarcić", "The teacher told him off for being late.", "Nauczyciel zbeształ go za spóźnienie."],
            ["think over", "przemyśleć", "I'll think over your proposal.", "Przemyślę Twoją propozycję."],
            ["throw away", "wyrzucić", "She threw away the old magazines.", "Wyrzuciła stare magazyny."],
            ["try on", "przymierzać", "She tried on several dresses before choosing one.", "Przymierzyła kilka sukienek, zanim wybrała jedną."],
            ["turn down", "odrzucić, ściszyć", "He turned down the job offer.", "Odrzucił ofertę pracy."],
            ["turn up", "pojawić się, podgłośnić", "He turned up late to the meeting.", "Pojawił się spóźniony na spotkaniu."],
            ["use up", "zużyć", "They used up all the paper in the office.", "Zużyli cały papier w biurze."],
            ["wake up", "obudzić się", "I wake up at 7 a.m. every day.", "Budzę się codziennie o 7 rano."],
            ["watch out", "uważać, być ostrożnym", "Watch out for cars when crossing the street.", "Uważaj na samochody, kiedy przechodzisz przez ulicę."],
            ["work out", "ćwiczyć, rozwiązać", "I work out at the gym three times a week.", "Ćwiczę na siłowni trzy razy w tygodniu."],
            ["write down", "zapisać", "Please write down your phone number.", "Proszę zapisz swój numer telefonu."],
            ["zip up", "zapiąć na zamek", "Zip up your jacket, it's cold outside.", "Zapinaj kurtkę, na dworze jest zimno."],
            ["zoom in", "powiększyć", "Can you zoom in on that picture?", "Czy możesz powiększyć to zdjęcie?"],
            ["zoom out", "pomniejszyć", "Let's zoom out to get a better view.", "Pomniejszmy, aby uzyskać lepszy widok."],
            ["check in", "zameldować się", "We checked in at the hotel at 3 p.m.", "Zameldowaliśmy się w hotelu o 15:00."],
            ["check out", "wymeldować się", "We need to check out by noon.", "Musimy się wymeldować do południa."],
            ["break up", "zerwać, rozstać się", "They broke up after three years together.", "Rozstali się po trzech latach razem."],
            ["break down", "zepsuć się, załamać się", "My car broke down on the way to work.", "Mój samochód zepsuł się w drodze do pracy."],
            ["break in", "włamać się", "Someone broke in while we were on vacation.", "Ktoś włamał się, gdy byliśmy na wakacjach."],
            ["break out", "uciec, wybuchnąć (o epidemii, wojnie)", "A fire broke out in the building last night.", "Ogień wybuchł w budynku zeszłej nocy."],
            ["call back", "oddzwonić", "I'll call you back later.", "Oddzwonię do ciebie później."],
            ["call off", "odwołać", "They called off the meeting due to bad weather.", "Odwołali spotkanie z powodu złej pogody."],
            ["calm down", "uspokoić się", "Calm down, everything will be fine.", "Uspokój się, wszystko będzie dobrze."],
            ["carry on", "kontynuować", "Let's carry on with the meeting.", "Kontynuujmy spotkanie."],
            ["carry out", "przeprowadzać, realizować", "They carried out the plan successfully.", "Zrealizowali plan z sukcesem."],
            ["catch up with", "nadrobić, dogonić", "I need to catch up with my work.", "Muszę nadrobić zaległości w pracy."],
            ["come across", "natknąć się na coś, spotkać przypadkiem", "I came across an old photo album.", "Natknąłem się na stary album ze zdjęciami."],
            ["come down with", "zachorować na", "She came down with a cold last week.", "Zachorowała na przeziębienie w zeszłym tygodniu."],
            ["come out", "wyjść na jaw, ukazać się", "The truth finally came out.", "Prawda w końcu wyszła na jaw."],
            ["come up with", "wymyślić, znaleźć rozwiązanie", "She came up with a brilliant idea.", "Wpadła na genialny pomysł."],
            ["cut down on", "ograniczyć", "I'm trying to cut down on sugar.", "Próbuję ograniczyć cukier."],
            ["cut off", "odciąć, przerwać", "They cut off the electricity.", "Odcięli prąd."],
            ["deal with", "radzić sobie z", "I have to deal with this issue immediately.", "Muszę natychmiast poradzić sobie z tym problemem."],
            ["dress up", "ubrać się elegancko, przebrać się", "We dressed up for the party.", "Ubraliśmy się elegancko na imprezę."],
            ["drop by", "wpaść z wizytą", "Why don't you drop by for coffee?", "Może wpadniesz na kawę?"],
            ["drop off", "podrzucić kogoś, zasnąć", "I'll drop you off at the station.", "Podrzucę cię na dworzec."],
            ["end up", "skończyć gdzieś, wylądować", "We ended up staying in a cheap hotel.", "Skończyliśmy w tanim hotelu."],
            ["fall apart", "rozpaść się, załamać się", "The chair fell apart when I sat on it.", "Krzesło rozpadło się, gdy na nim usiadłem."],
            ["fall for", "zakochać się, dać się nabrać", "He fell for her the moment he saw her.", "Zakochał się w niej, gdy tylko ją zobaczył."],
            ["fall out", "pokłócić się, wypaść", "They fell out over a minor disagreement.", "Pokłócili się o drobnostkę."],
            ["find out", "dowiedzieć się", "I found out the truth yesterday.", "Dowiedziałem się prawdy wczoraj."],
            ["focus on", "skupić się na", "You need to focus on your studies.", "Musisz skupić się na nauce."],
            ["get away", "uciec, wyrwać się", "We need to get away for a few days.", "Musimy wyrwać się na kilka dni."],
            ["get back", "wrócić", "When did you get back from your trip?", "Kiedy wróciłeś z podróży?"],
            ["get over", "dojść do siebie, przezwyciężyć", "It took her a long time to get over the breakup.", "Zajęło jej dużo czasu dojście do siebie po rozstaniu."],
            ["give in", "ustąpić, poddać się", "He finally gave in to their demands.", "W końcu ustąpił ich żądaniom."],
            ["go after", "dążyć do czegoś, ścigać", "He went after his dreams despite the obstacles.", "Dążył do swoich marzeń mimo przeszkód."],
            ["go away", "odejść, wyjechać", "They went away for the weekend.", "Wyjechali na weekend."],
            ["go back", "wrócić", "We need to go back to the basics.", "Musimy wrócić do podstaw."],
            ["go out", "wyjść, spotykać się towarzysko", "Do you want to go out tonight?", "Chcesz wyjść dziś wieczorem?"],
            ["go through", "przejść przez coś, przejrzeć", "She's going through a tough time.", "Przechodzi przez trudny okres."],
            ["grow up", "dorastać", "He grew up in a small village.", "Dorastał w małej wiosce."],
            ["hand in", "oddać (pracę, dokument)", "Please hand in your assignments on time.", "Proszę oddać zadania na czas."],
            ["hand over", "przekazać coś komuś", "He handed over the keys to the new owner.", "Przekazał klucze nowemu właścicielowi."],
            ["hang on", "czekać chwilę", "Hang on, I'll be with you in a moment.", "Poczekaj chwilę zaraz do ciebie wrócę."],
            ["hang out", "spędzać czas", "Do you want to hang out this weekend?", "Chcesz spędzić czas razem w ten weekend?"],
            ["hold on", "trzymać się, czekać", "Hold on tight we're going fast.", "Trzymaj się mocno jedziemy szybko."],
            ["keep on", "kontynuować, robić coś dalej", "Keep on studying you're almost there.", "Kontynuuj naukę jesteś prawie u celu."],
            ["let down", "zawieść, rozczarować", "Don't let me down this time.", "Nie zawiedź mnie tym razem."],
            ["look after", "opiekować się", "Can you look after the kids tonight?", "Czy możesz zająć się dziećmi dziś wieczorem?"],
            ["look back on", "wspominać", "She often looks back on her childhood.", "Często wspomina swoje dzieciństwo."],
            ["look for", "szukać", "I'm looking for my glasses.", "Szukam swoich okularów."],
            ["look forward to", "nie móc się doczekać", "I'm looking forward to our vacation.", "Nie mogę się doczekać naszych wakacji."],
            ["look out", "uważać, być ostrożnym", "Look out, there's a car coming!", "Uważaj nadjeżdża samochód!"],
            ["make up", "zmyślić, pogodzić się", "She made up a story to explain her absence.", "Wymyśliła historię, aby wytłumaczyć swoją nieobecność."],
            ["move on", "przejść do czegoś nowego", "It's time to move on and start fresh.", "Czas iść dalej i zacząć od nowa."],
            ["pay back", "spłacić, oddać pieniądze", "I'll pay you back next week.", "Oddam ci pieniądze w przyszłym tygodniu."],
            ["pick up", "podnieść, odebrać (telefon)", "Can you pick up the phone?", "Możesz odebrać telefon?"],
            ["point out", "zwrócić uwagę, wskazać", "He pointed out a mistake in the report.", "Wskazał błąd w raporcie."],
            ["put off", "odłożyć, przełożyć", "They put off the meeting until next week.", "Przełożyli spotkanie na przyszły tydzień."],
            ["put on", "założyć, przybrać (na wadze)", "She put on her coat before leaving.", "Założyła płaszcz przed wyjściem."],
            ["put up with", "znosić coś, tolerować", "I can't put up with this noise anymore.", "Nie mogę już znieść tego hałasu."],
            ["run into", "wpaść na kogoś, spotkać przypadkiem", "I ran into an old friend at the store.", "Wpadłem na starego znajomego w sklepie."],
            ["run out of", "skończyć się, wyczerpać", "We've run out of milk.", "Skończyło nam się mleko."],
            ["set off", "wyruszyć, rozpocząć podróż", "We set off early to avoid traffic.", "Wyruszyliśmy wcześnie, żeby uniknąć korków."],
            ["set up", "założyć, ustawić", "They set up a new company last year.", "Założyli nową firmę w zeszłym roku."],
            ["show off", "popisywać się", "He's always showing off his new gadgets.", "Zawsze popisuje się swoimi nowymi gadżetami."],
            ["shut down", "zamknąć, wyłączyć", "They shut down the factory last month.", "Zamknęli fabrykę w zeszłym miesiącu."],
            ["sort out", "rozwiązać, uporządkować", "We need to sort out this problem soon.", "Musimy szybko rozwiązać ten problem."],
            ["take after", "być podobnym do", "She takes after her mother.", "Jest podobna do swojej matki."],
            ["take off", "wystartować, zdjąć (ubranie)", "The plane took off on time.", "Samolot wystartował na czas."],
            ["take on", "podjąć się, zatrudnić", "They're taking on new staff.", "Zatrudniają nowych pracowników."],
            ["take over", "przejąć, zdobyć kontrolę", "He took over the family business.", "Przejął rodzinny interes."],
            ["take up", "podjąć, zacząć (hobby)", "I've taken up yoga recently.", "Ostatnio zacząłem ćwiczyć jogę."],
            ["think through", "przemyśleć, rozważyć", "Let's think through all the possibilities.", "Przemyślmy wszystkie możliwości."],
            ["try out", "wypróbować", "I'm going to try out this new recipe.", "Wypróbuję ten nowy przepis."],
            ["turn into", "przemienić się, zamienić w", "The caterpillar turned into a butterfly.", "Gąsienica zamieniła się w motyla."],
            ["turn out", "okazać się, wypaść", "It turned out to be a great day.", "Okazało się, że to był wspaniały dzień."],
            ["turn up", "pojawić się, zjawić się", "She turned up at the party uninvited.", "Pojawiła się na imprezie bez zaproszenia."],
            ["wake up", "obudzić się", "I wake up at 6 a.m. every day.", "Budzę się codziennie o 6 rano."],
            ["warm up", "rozgrzać się", "Don't forget to warm up before exercising.", "Nie zapomnij się rozgrzać przed ćwiczeniami."],
            ["work out", "ćwiczyć, rozwiązać (problem)", "We need to work out a solution.", "Musimy znaleźć rozwiązanie."],
            ["write down", "zapisać", "Can you write down the instructions?", "Czy możesz zapisać instrukcje?"],
        

            ['11111', '111111'],
            ['11111', '111111'],
        ]

        ];

}
