<?php

namespace App\Langs\levels\SchoolBook;

use App\Langs\BaseLevel;

/**
 * Created by PhpStorm.
 * User: Roman Pytka
 * Date: 2/28/21
 * Time: 8:23 AM
 */

class Eighth extends BaseLevel
{
    public $title = 'Świat przyrody';
    public $desc = 'moduł ósmy';
    public $slug = 'the-natural-word';
    public $data = [
        'geographical_features' => [
            ['beach', 'plaża'],
            ['coast', 'wybrzeże, brzeg'],
            ['continent', 'kontynent'],
            ['desert', 'pustynia'],
            ['field', 'pole'],
            ['forest', 'las'],
            ['geographical feature', 'elementy krajobrazu naturalnego'],
            ['hill', 'wzgórze'],
            ['island', 'wyspa'],
            ['lake', 'jezioro'],
            ['mountain', 'góry'],
            ['mountain range', 'pasmo górskie'],
            ['mountain top', 'szczyt górski'],
            ['ocean', 'ocean'],
            ['rainforest', 'las deszczowy'],
            ['river', 'rzeka'],
            ['sea', 'morze'],
            ['valley', 'dolina'],
            ['waterfall', 'wodospad'],
            ['deep', 'głęboki'],
            ['dense', 'gęsty'],
            ['fast-flowing', 'wartki'],
            ['high', 'wysoki'],
            ['narrow', 'wąski'],
            ['stark', 'nagi, surowy'],
            ['vast', 'ogromny'],
            ['steep', 'stromy'],
            ['wide', 'szeroki'],
            ['winding', 'wijący się, kręty'],
            

        ],
        'animals' => [
            ['animal', 'zwierzę'],
            ['ant', 'mrówka'],
            ['bear', 'niedźwiedź'],
            ['bee', 'pszczoła'],
            ['beetle', 'chrząszcz'],
            ['cockchafer', 'chrabąszcz'],
            ['bird', 'ptak'],
            ['butterfly', 'motyl'],
            ['cattle', 'bydło'],
            ['cheetah', 'gepart'],
            ['cow', 'krowa'],
            ['crocodile', 'krokodyl'],
            ['dolphin', 'delfin'],
            ['eagle', 'orzeł'],
            ['elephant', 'słoń'],
            ['fly', 'mucha'],
            ['giraffe', 'żyrafa'],
            ['goat', 'koza'],
            ['gorilla', 'goryl'],
            ['insect', 'owad'],
            ['horse', 'koń'],
            ['land mammal', 'ssak lądowy'],
            ['leopart', 'lampart'],
            ['lion', 'lew'],
            ['lizard', 'jaszczurka'],
            ['monkey', 'małpa'],
            ['mosquito', 'komar'],
            ['moth', 'ćma'],
            ['octopus', 'ośmiornica'],
            ['ostrich', 'struś'],
            ['owl', 'sowa'],
            ['parrot', 'papuga'],
            ['penguin', 'pingwin'],
            ['reptile', 'gad'],
            ['scorpion', 'skorpion'],
            ['sea creature', 'stworzenie morskie'],
            ['shark', 'rekin'],
            ['sheep', 'owca'],
            ['snake', 'wąż'],
            ['poisonous snake', 'wąż jadowity'],
            ['starfish', 'rozgwiazda'],
            ['swallow', 'jaskółka'],
            ['tiger', 'tygrys'],
            ['tortoise', 'żółw'],
            ['wasp', 'osa'],
            ['whale', 'wieloryb'],
            ['wolf', 'wilk'],
            ['beak', 'dziób'],
            ['claw', 'pazur'],
            ['feather', 'pióro'],
            ['fur', 'futro'],
            ['paw', 'łapa'],
            ['shell', 'skorupa'],
            ['skin', 'skóra'],
            ['species', 'gatunek'],
            ['tail', 'ogon'],
            ['teeth', 'zęby'],
            ['trunk', 'trąba słonia'],
            ['wing', 'skrzydło'],        


        ],
        'plants' => [
            ['branch', 'gałąź'],
            ['bush', 'krzew'],
            ['flower', 'kwiat'],
            ['fruit', 'owoc'],
            ['garden', 'ogród'],
            ['grass', 'trawa'],
            ['leaf', 'liść'],
            ['leaves', 'liście'],
            ['plants', 'rośliny'],
            ['grow plants', 'uprawiać rośliny'],
            ['water plants', 'podlewać rośliny'],
            ['pot plant', 'kwiat doniczkowy'],
            ['seed', ' nasienie, ziarno'],
            ['tree', 'drzewo'],
            ['vegetable', 'warzywo'],
            ['weed', 'chwast'],
            
        
        ],
        'the_weather' => [
            ['cold', 'zimny'],
            ['icy', 'lodowaty'],
            ['chilly', 'chłodny'],
            ['cloud', 'chmura'],
            ['cloudless', 'bezchmurny'],
            ['cloudy', 'pochmurny'],
            ['cool', 'chłodny'],
            ['dry', 'suchy'],
            ['fog', 'mgła'],
            ['foggy', 'mglisty'],
            ['hot', 'gorący'],
            ['it\'s boiling', 'jest bardzo gorąco'],
            ['it\'s freezing, it\'s icy', 'mroźno'],
            ['it\'s shining', 'świeci słońce'],
            ['it\'s raining', 'pada deszcz'],
            ['it\'s snowing', 'pada śnieg'],
            ['rain', 'deszcz'],
            ['snow', 'śnieg'],
            ['stormy', 'burzowy'],
            ['sun ', 'słońce'],
            ['sunny', 'słoneczny'],
            ['thunderstorm', 'burza z piorunami'],
            ['warm', 'ciepły'],
            ['bright weather', 'słoneczna pogoda'],
            ['fine weather, nice weather', 'ładna pogoda'],
            ['terrible weather', 'okropna pogoda'],
            ['weather forecast', 'prognoza pogody'],
            ['wind', 'wiater'],
            ['windy', 'wietrzny'],
            ['autumn', 'jesień'],
            ['spring', 'wiosna'],
            ['summer', 'lato'],
            ['winter', 'zima'],
            
                 
        ],
        'extreme_weather_and_natural_disaster' => [
            ['avalanche', 'lawina'],
            ['blizzard', 'zamieć'],
            ['drought', 'susza'],
            ['erupt', 'wybuchać'],
            ['earthquake', 'trzęsienie ziemi'],
            ['extreme weather', 'pogoda ekstremalna'],
            ['flood', 'powódź'],
            ['hurricane', 'huragan'],
            ['natural disaster', 'klęska żywiołowa'],
            ['tornado', 'tornado'],
            ['tsunami', 'tsunami'],
            ['hight wave', 'wysoka fala'],
            ['volcano', 'wulkan'],
            ['be badly affected' , 'zostać boleśnie dotkniętym'],
            ['casualties', 'ofiary'],
            ['emergency services', 'służby ratunkowe'],
            ['evacuate', 'ewakuować'],
            ['leave the area', 'opuścić teren'],
            ['rescue people', 'ratować ludzi'],
        ],
        'environmental_problems' => [
            ['acid rain', 'kwaśny deszcz'],
            ['car exhaust fumes', 'spaliny samochodowe'],
            ['climate change', 'zmiany klimatyczne'],
            ['drop litter', 'pozostawiać śmieci'],
            ['endangered animals', 'zwirzęta zagrożone wyginięciem'],
            ['environmental problems', 'problemy środowiska naturalnego'],
            ['global warming', 'globalne ocieplenie'],
            ['greenhouse effect', 'efekt cieplarniany'],
            ['holes in the ozone layer', 'dziury w powłoce ozonowej'],
            ['kill wildlife', 'zabijać dzikie zwierzęta'],
            ['garbage dump', 'wysypisko śmieci'],
            ['cutting down trees', 'wycinanie drzew'],
            ['oil spill', 'wyciek ropy'],
            ['air pollution', 'zanieczyszczenie powietrza'],
            ['water pollution', 'zanieczyszczenie wody'],
            ['take away the natural habitat of animals', 'odbierać zwierzętom ich środowisko naturalne'],
            ['waste', 'odpady, odpadki'],
            

        ],
        'environmental_solutions' => [
            ['conservation', 'ochrona'],
            ['eco-friendly', 'przyjazny dla środowiska'],
            ['electric car', 'samochód elektryczny'],
            ['help for the environment', 'pomoc dla środowiska'],
            ['organic food', 'żywność naturalna'],
            ['pick up litter', 'zbierać śmieci'],
            ['protect the environment', 'chronić środowisko naturalne'],
            ['provide public transport', 'zapewnić transport publiczny'],
            ['recycling', 'utylizacja'],
            ['save electricity', 'oszczędzać elektryczność'],
            ['save water', 'oszczędzać wodę'],
            ['solar power', 'energia słoneczna'],
            ['sort out rubbish', 'segregować śmieci'],
            ['use less fuel', 'używać mniej paliwa'],
            ['turn lights off', 'wyłączać światło'],
            ['wind farm', 'farma wiatrowa'],        

        ],


    ];

}
