<?php

namespace App\Langs\levels\SchoolBook;

use App\Langs\BaseLevel;

/**
 * Created by PhpStorm.
 * User: Roman Pytka
 * Date: 2/28/21
 * Time: 8:23 AM
 */

class Fourtheenth extends BaseLevel
{
    public $title = 'Żywienie';
    public $desc = 'moduł czternasty';
    public $slug = 'nutrition';
    public $data = [
        'food' => [
            ['bacon', 'bekon'],
            ['beef', 'wołowina'],
            ['chicken', 'kurczak'],
            ['ham', 'szynka'],
            ['meat', 'mięso'],
            ['pork', 'wieprzowina'],
            ['sausage', 'kiełbasa'],
            ['turkey', 'indyk'],
            ['cod', 'dorsz'],
            ['fish', 'ryba'],
            ['herring', 'śledź'],
            ['prawn', 'krewetka'],
            ['salmon', 'łosoś'],
            ['seafood', 'owoce morza'],
            ['tuna', 'tuńczyk'],
            ['butter', 'masło'],
            ['cheese', 'ser'],
            ['cream', 'śmietana'],
            ['egg', 'jajko'],
            ['margarine', 'margaryna'],
            ['yoghurt', 'jogurt'],
            ['bread', 'chleb'],
            ['cereal', 'płatki śniadaniowe'],
            ['cereal products', 'produkty zbożowe'],
            ['flour', 'mąka'],
            ['pasta', 'makaron'],
            ['rice', 'ryż'],
            ['roll', 'bułka'],
            ['apple', 'jabłko'],
            ['apricot', 'morela'],
            ['banana', 'banan'],
            ['blackcurrant', 'czarna porzeczka'],
            ['blueberry', 'jagoda'],
            ['cherry', 'wiśnia'],
            ['coconut', 'kokos'],
            ['fruit', 'owoce'],
            ['grape', 'winogrono'],
            ['lime', 'limonka'],
            ['lemon', 'cytryna'],
            ['orange', 'pomarańcza'],
            ['pear', 'gruszka'],
            ['peach', 'brzoskwinia'],
            ['pineapple', 'ananas'],
            ['raspberry', 'malina'],
            ['strawberry', 'truskawka'],
            ['watermelon', 'arbuz'],
            ['aubergine', 'bakłażan'],
            ['beans', 'fasola'],
            ['broccoli', 'brokuł'],
            ['cabbage', 'kapusta'],
            ['carrot', 'marchew'],
            ['cauliflower', 'kalafior'],
            ['cucumber', 'ogórek'],
            ['garlic', 'czosnek'],
            ['green peas', 'groszek'],
            ['leek', 'por'],
            ['lettuce', 'sałata'],
            ['mushrooms', 'grzyby'],
            ['onion', 'cebula'],
            ['olive', 'oliwka'],
            ['pepper', 'papryka'],
            ['vegetable', 'jarzyna'],
            ['potato', 'ziemiak'],
            ['tomato', 'pomidor'],
            ['beer', 'piwo'],
            ['coffee', 'kawa'],
            ['drink', 'napój'],
            ['juice', 'sok'],
            ['soft drinks', 'napoje bezalkocholowe'],
            ['tea', 'herbata'],
            ['sparkling water', 'woda gazowana'],
            ['still water', 'woda niegazowana'],
            ['alcoholic drinks', 'napoje alkocholowe'],
            ['wine', 'wino'],
            ['apple pie', 'szarlotka'],
            ['biscuits, cookies', 'ciastka'],
            ['cake', 'ciasto'],
            ['cheesecake', 'sernik'],
            ['chocolate', 'czekolada'],
            ['ice cream', 'lody'],
            ['pancake', 'naleśnik'],
            ['black pepper ', 'czarny pieprz'],
            ['ketchup, tomatoe sauce', 'keczup'],
            ['mayonnaise', 'majonez'],
            ['oil', 'olej'],
            ['olive oil', 'oliwa'],
            ['salad dressing', 'sos do sałatek'],
            ['salt', 'sól'],
            ['spices', 'przyprawy'],
            ['sugar', 'cukier'],
            ['vinegar', 'ocet'],
        ],
        'food_quantities' => [
            ['bar of chocolates', 'tabliczka czekolady'],
            ['bottle of water', 'butelka wody'],
            ['bowl of soup', 'miska zupy'],
            ['box of cereal', 'pudełko płatków śniadaniowych'],
            ['carton of milk', 'karton mleka'],
            ['cup of coffee', 'filiżanka kawy'],
            ['glass of water', 'szklanka wody'],
            ['jar of jam', 'słoik dżemu'],
            ['loaf of bread', 'bochenek chleba'],
            ['slice of bread', 'kromka chleba'],
            ['spoonful of sugar', 'łyżeczka cukru'],
            ['packet of crisps', 'paczka czipsów'],
            ['piece of fruit', 'kawałek owocu'],
            ['tub of margarine', 'kostka margaryny'],
            ['tube of tomato puree', 'tubka koncentratu pomidorowego'],
            

        ],
        'taste' => [
            ['bitter', 'gorzki'],
            ['dry wine', 'wino wytrawne'],
            ['fatty food', 'tłuste jedzenie'],
            ['fresh', 'świeży'],
            ['hot, spicy', 'ostry, pikantny'],
            ['lean meat', 'chude mięso'],
            ['mild', 'łagodny, nieostry'],
            ['plain', 'zwyczajny, nie doprawiony'],
            ['salty', 'słony'],
            ['sour', 'kwaśny'],
            ['steak', 'stek'],
            ['medium-cooked', 'średnio wysmażony'],
            ['rare steak', 'nie dosmażony stek'],
            ['well-done steak', 'dobrze wysmażony stek'],
            ['strong tea', 'mocna herbata'],
            ['sweet', 'słodki'],
            ['taste', 'smak'],
            ['weak coffee', 'słaba kawa'],
        ],
        'meals' => [
            ['be hungry', 'być głodnym'],
            ['be full', 'byś najedzonym'],
            ['breakfast', 'śniadanie'],
            ['dinner', 'obiad'],
            ['lunch', 'lunch'],
            ['food', 'jedzenie'],
            ['meal', 'posiłek'],
            ['packed lunch', 'drugie śniadanie'],
            ['snack', 'przekąska'],
            ['supper', 'kolacja'],
                 
        ],
        'the_food_pyramid' => [
            ['carbohydrates', 'węglowodany'],
            ['fats', 'tłuszcze'],
            ['food pyramid', 'piramida żywieniowa'],
            ['minerals', 'minerały'],
            ['protein', 'białko'],
            ['vitamins', 'witaminy'],
           
        ],
        'in_a_restaurant' => [
            ['ask for the menu', 'prosić o kartę dań'],
            ['bill', 'rachunek'],
            ['book a table', 'zarezerwować stolik'],
            ['dessert', 'deser'],
            ['dish', 'potrawa'],
            ['eat out', 'jeść poza domem'],
            ['excellent food', 'doskonałe jedzenie'],
            ['good atmosphere', 'dobra atmosfera'],
            ['have a cup of coffee', 'wypić filiżankę kawy'],
            ['leave a tip', 'zostawić napiwek'],
            ['main course', 'danie główne'],
            ['nice decor', 'ładny wystrój'],
            ['order a meal', 'zamawiać posiłek'],
            ['reasonable prices', 'przystępne ceny'],
            ['service', 'obsługa'],
            ['starter', 'przystawka'],
            ['cafe', 'kawiarnia'],
            ['canteen', 'stołówka'],
            ['restaurant', 'restauracja'],
            ['italian restaurant', 'restauracja włoska'],
            ['fast food restaurant', 'restauracja fast food'],
            ['snack bar', 'bar'],
            ['bowl', 'miska'],
            ['fork', 'widelec'],
            ['glass', 'szklanka, keliszek'],
            ['knife', 'nóż'],
            ['mug', 'kubek'],
            ['plate', 'talerz'],
            ['spoon', 'łyżka'],
            ['teaspoon', 'łyżeczka'],
        ],
        'parties' => [
            ['barbeque', 'gril'],
            ['dinner party', 'uroczysta kolacja'],
            ['fancy dress party', 'bal maskowy'],
            ['host', 'gospodarz'],
            ['hostess', 'gospodyni'],
            ['picnic', 'piknik'],  
        ],

        'cooking' => [
            ['add', 'dodawać'],
            ['bake', 'piec'],
            ['break eggs', 'rozbijać jaja'],
            ['chop', 'siekać'],
            ['cool', 'chłodzić'],
            ['cut', 'kroić'],
            ['grate', 'trzeć, ruszt'],
            ['mix', 'mieszać'],
            ['peel', 'obierać'],
            ['pour', 'nalewać'],
            ['roast', 'piec'],
            ['shake', 'wstrząsnąć'],
            ['sprinkle', 'posypywać, kropić'],
            ['squeeze', 'wyciskać'],
            ['whisk', 'ubijać'],
        ],

    

    ];

}
