<?php

namespace App\Langs\levels\SchoolBook;

use App\Langs\BaseLevel;

/**
 * Created by PhpStorm.
 * User: Roman Pytka
 * Date: 2/28/21
 * Time: 8:23 AM
 */

class Theerteenth extends BaseLevel
{
    public $title = 'Praca';
    public $desc = 'moduł trzynasty';
    public $slug = 'job';
    public $data = [
        'jobs' => [
            ['accountant', 'księgowy'],
            ['air traffic controller', 'kontroler ruchu powietrznego'],
            ['architect', 'architekt'],
            ['au pair, babysitter', 'opiekun do dzieci'],
            ['businessman', 'biznesmen'],
            ['businesswoman', 'bizneswoman'],
            ['car mechanic', 'mechanik samochodowy'],
            ['cashier', 'kasjer'],
            ['coach', 'trener'],
            ['computer programmer', 'programista komputerowy'],
            ['chef', 'szef kuchni'],
            ['dentist', 'dentysta'],
            ['doctor', 'lekarz'],
            ['electrician', 'elektryk'],
            ['entrepreneur', 'przedsiębiorca'],
            ['estate agent', 'agent nieruchomości'],
            ['farmer', 'rolnik'],
            ['hairdresser', 'fryzjer'],
            ['film director', 'reżyser filmowy'],
            ['financial manager', 'kierownik finansowy'],
            ['fire fighter', 'strażak'],
            ['food critic', 'krytyk kulinarny'],
            ['interior designer', 'projektant wnętrz'],
            ['journalist', 'dzinnikarz'],
            ['judge', 'sędzia'],
            ['lawyer', 'adwokat'],
            ['librarian', 'bibliotekarz'],
            ['lorry driver', 'kierowca ciężarówki'],
            ['manager', 'kierownik'],
            ['miner', 'górnik'],
            ['model', 'model'],
            ['musician', 'muzyk'],
            ['nurse', 'pielęgniarka'],
            ['painter', 'malarz'],
            ['paramedic', 'ratownik medyczny'],
            ['pharmacist', 'farmaceuta'],
            ['photographer', 'fotograf'],
            ['pilot', 'pilot'],
            ['police officer', 'policjant'],
            ['politician', 'polityk'],
            ['plumber', 'hydraulik'],
            ['postman', 'listonosz'],
            ['receptionist', 'recepcjonista'],
            ['salesman', 'sprzedawca'],
            ['secretary', 'sekretarz'],
            ['security guard', 'pracownik ochrony'],
            ['social worker', 'pracownik społeczny'],
            ['stockbroker', 'makler giełdowy'],
            ['surgeon', 'chirurg'],
            ['taxi driver', 'taksówkarz'],
            ['teacher', 'nauczyciel'],
            ['ticket inspector', 'kontroler biletów'],
            ['translator', 'tłumacz'],
            ['travel agent', 'agent biura podróży'],
            ['vet', 'weterynarz'],
            ['waiter', 'kelner'],
            ['waitress', 'kelnerka'],
            ['writer', 'pisarz'],
            ['although', 'mimo że'],
            
                     

        ],
        'adjectives_to_describe_a_job' => [
            ['adjectives', 'przymiotniki'],
            ['describe', 'opisać'],
            ['badly paid', 'źle płatna'],
            ['boring, dull', 'nudna'],
            ['full-time', 'w pełnym wymiarze godzin'],
            ['manual', 'fizyczna'],
            ['part-time', 'na pół etatu, na część etatu'],
            ['permanent', 'stała'],
            ['sedentery', 'siedząca'],
            ['satisfying', 'satysfakcjonująca'],
            ['stressful', 'stresująca'],
            ['temporary', 'tymczasowa'],
            ['tiring', 'męcząca'],
            ['well-paid', 'dobrze płatna'],            

        ],
        'adjectives_to_describe_people' => [
            ['communicative', 'rozmowny, komunikatywny'],
            ['compenent', 'kompetentny'],
            ['confident', 'pewny siebie'],
            ['courageous', 'odważny'],
            ['creative', 'twórczy'],
            ['determined', 'zdecydowany'],
            ['flexible', 'elastyczny'],
            ['honest', 'uczciwy'],
            ['knowledgeable', 'z dużą wiedzą'],
            ['patient', 'cierpliwy'],
            ['responsible', 'odpowidzielny'],
            ['sensitive', 'wrażliwy'],
            ['sociable', 'towarzyski'],
            ['strong', 'silny'],
            ['talented', 'utalentowany'],
        ],
        'applying_for_a_job' => [
            ['apply for a job', 'starać się o pracę'],
            ['candidate', 'kandydatura'],
            ['covering letter', 'list motywacyjny'],
            ['curriculum vitae', 'życiorys'],
            ['experience', 'doświadczenie'],
            ['fill in a form', 'wypełnić formularz'],
            ['job application', 'podanie o pracę'],
            ['job center', 'biuro pośrednictwa pracy'],
            ['job offer', 'oferta pracy'],
            ['accept a job', 'przyjąć pracę'],
            ['get a job', 'dostać pracę'],
            ['turn down job', 'odrzucić pracę'],
            ['have a degree in sth', 'posiadać wykształcenie w jakiejś dzienienie'],
            ['have good IT skills', 'potrafić dobrze obsługiwać komputer'],
            ['interview', 'rozmowa kwalifikacyjna'],
            ['interviewer', 'osoba przeprowadzająca rozmowę kwalifikacyjną'],
            ['job advertisement', 'ogłoszenie o pracę'],
            ['look for a job', 'szukać pracy'],
            ['offer sb a job', 'proponować komuś pracę'],
            ['qualifications', 'kwalifikacje'],
            ['recruitment', 'rekrutacja'],
            ['references', 'referencje'],
            ['sign a contract', 'podpisać umowę'],
            ['skills', 'umiejętności'],
            ['start work', 'rozpocząć pracę'],
            ['vacancy', 'wolna posada'],
                 
        ],
        'at_work' => [
            ['boss', 'szef'],
            ['career', 'kariera'],
            ['challenge', 'wyzwanie'],
            ['colleague', 'kolega z pracy'],
            ['department', 'dział'],
            ['finance department', 'dział finansowy'],
            ['human resource department', 'dział zasobów ludzkich'],
            ['marketing department', 'dział marketingu'],
            ['sales department', 'dział sprzedaży'],
            ['deadline', 'termin wykonania pracy'],
            ['duty', 'obowiązek'],
            ['employee', 'pracownik'],
            ['employer', 'pracodawca'],
            ['living expenses', 'koszty utrzymania'],
            ['manager', 'kierownik'],
            ['office', 'biuro'],
            ['pay', 'płaca'],
            ['position', 'stanowisko'],
            ['salary', 'pensja'],
            ['staff', 'personel'],
            ['tip', 'napiwek'],
            ['wages', 'zapłata tygodniowa, płaca, wynagrodzenie'],
            ['working conditions', 'warunki pracy'],
            ['working hours', 'godziny pracy'],
            ['workplace', 'miejsce pracy'],
            ['be part of team', 'być częścią zespołu'],
            ['be on sick leave', 'być na zwolnieniu lekarskim'],
            ['be promoted, get promoted', 'otrzymać awans'],
            ['be self-employed', 'prowadzić własną działalność'],
            ['do overtime', 'pracować w nadgodzinach'],
            ['get a bonus', 'dostać premię'],
            ['get a job', 'dostać pracę'],
            ['get a pay rise', 'dostać podwyżkę'],
            ['get a promoted', 'dostać awans'],
            ['get sacked', 'zostać zwolnionym'],
            ['make a lot of money', 'dużo zarabiać'],
            ['take a day off', 'brać dzień wolny'],
            ['take leave', 'brać urlop'],
            ['take over from sb', 'przejmować od kogoś obowiązki'],
            ['work as a teacher', 'pracować jako nauczyciel'],
            ['work freelance', 'pracować na umowę o dzieło'],
            ['work for a company', 'pracować dla firmy'],
            ['work long hours', 'pracować w nadgodzinach'],
            ['work shifts', 'pracować na zmianę'],
           
        ],
        'out_of_work' => [
            ['be fired', 'zostać wyrzuconym z pracy'],
            ['give up a job', 'rzucić pracę'],
            ['go on strike', 'strajkować'],
            ['lay sb off', 'zwolnić kogoś'],
            ['out of work', 'bez pracy'],
            ['pension', 'emerytura'],
            ['retire', 'przejść na emeryturę'],
            ['unemployed', 'bezrobotny'],
            ['unemployment', 'bezrobocie'],
            ['melt', 'topnieć'],
        ],
        

    ];

}
