<?php

namespace App\Langs\levels;

use App\Langs\BaseLevel;

/**
 * Created by PhpStorm.
 * User: Roman Pytka
 * Date: 2/28/21
 * Time: 8:23 AM
 */

class Eleventh extends BaseLevel
{
    public $title = 'Kultura';
    public $desc = 'moduł jedenasty';
    public $slug = 'culture';
    public $data = [
        'film' => [
            ['actor', 'aktor'],
            ['actress', 'aktorka'],
            ['adaptation', 'adaptacja'],
            ['be set in', 'rozgrywać się w'],
            ['blockbuster', 'hit filmowy'],
            ['cartoon film', 'kreskówka, film animowany'],
            ['cast', 'obsada'],
            ['cinema', 'kino'],
            ['comedy', 'komedia'],
            ['director', 'reżyser'],
            ['favourite character', 'ulubiona postać'],
            ['film, movie', 'film'],
            ['advanture film, action film', 'film akcji'],
            ['documentary film', 'film dokumentalny'],
            ['fantasy film', 'film fantastyczny'],
            ['feature film', 'film fabularny'],
            ['horror film', 'film horror'],
            ['romantic film', 'film romantyczny'],
            ['science fiction film', 'film science-fiction'],
            ['war film', 'film wojenny'],
            ['hero', 'bohater'],
            ['heroine', 'bohaterka'],
            ['historical drama', 'dramat historyczny'],
            ['leading role', 'główna rola'],
            ['make a film', 'kręcić film'],
            ['battle scene', 'scena bitwy'],
            ['screenplay', 'scenariusz'],
            ['soundtrack', 'ścieżka dźwiękowa'],
            ['special effects', 'efekty specjalne'],
            ['star', 'gwiazda'],
            ['star in a film', 'występować w filmie'],
            ['story', 'historia'],
            ['stunt', 'wyczyn kaskaderski'],
            ['subtitles', 'napisy na filmie'],
            ['thriller', 'dreszczowiec'],
            ['western', 'western'],
    
        ],
        'literature' => [
            ['author', 'autor'],
            ['autobiography', 'autobiografia'],
            ['bestseller', 'bestseler'],
            ['biography', 'biografia'],
            ['chapter', 'rozdział'],
            ['character', 'postać'],
            ['cover', 'okładka'],
            ['contents', 'treść, zawartość'],
            ['detective story, crime story', 'kryminał'],
            ['fiction', 'literatura piękna'],
            ['illustration', 'ilustracja'],
            ['illustrator', 'ilustrator'],
            ['literature', 'literatura'],
            ['narrator', 'narrator'],
            ['non-fiction', 'literatura faktu'],
            ['novel', 'powieść'],
            ['novelist', 'powieściopisarz'],
            ['play', 'sztuka'],
            ['plot', 'akcja, wątek'],
            ['poet', 'poeta'],
            ['poetry', 'poezja'],
            ['short story', 'opowiadanie'],
            ['title', 'tytuł'],
        ],
        'art' => [
            ['abstract', 'abstrakcyjny'],
            ['art', 'sztuka'],
            ['art gallery', 'galeria sztuki'],
            ['artist', 'artysta'],
            ['canvas', 'płótno'],
            ['caricature', 'karykatura'],
            ['cartoon', 'rysunek satyryczny'],
            ['collage', 'kolaż'],
            ['designer', 'projektant'],
            ['drawing', 'rysunek'],
            ['exhibition', 'wystawa'],
            ['frame', 'ramka'],
            ['graffiti', 'graffiti'],
            ['graphic design', 'grafika'],
            ['landscape', 'pejzaż'],
            ['masterpiece', 'arcydzieło'],
            ['mural', 'malowidło ścienne'],
            ['painting', 'malarstwo'],
            ['photographer', 'fotograf'],
            ['photography', 'fotografia'],
            ['picture', 'obraz'],
            ['portrait', 'portret'],
            ['realistic', 'realistyczny'],
            ['sculpture', 'rzeźba'],
            ['sketch', 'szkic'],
            ['still life', 'martwa natura'],
        ],
        'adjectives' => [
            ['amazing', 'zdumiewający'],
            ['beautiful', 'piękny'],
            ['boring', 'nudny'],
            ['bright', 'jasny'],
            ['colourful', 'kolorowy'],
            ['creative', 'twórczy'],
            ['disappointing', 'rozczarowujący'],
            ['dull', 'nudny'],
            ['exciting', 'podniecający'],
            ['frightening', 'przerażający'],
            ['funny', 'śmieszny'],
            ['imaginative', 'z wyobraźnią'],
            ['interesting', 'ciekawy'],
            ['messy', 'nieporządny, niechlujny'],
            ['moving', 'poruszający'],
            ['original', 'oryginalny'],
            ['ugly', 'brzydki'],
            ['unusual', 'nietypowy'],
                 
        ],
        'music' => [
            ['record an album', 'nagrać album muzyczny'],
            ['release an album', 'wydać album muzyczny'],
            ['band', 'grupa, zespół'],
            ['choir', 'chór'],
            ['compose', 'komponować'],
            ['composer', 'kompozytor'],
            ['concert', 'koncert'],
            ['concert hall', 'sala koncertowa'],
            ['conductor', 'dyrygent'],
            ['festival', 'festiwal, kiermasz'],
            ['hit', 'przebój'],
            ['musical instruments', 'intrumenty muzyczne'],
            ['brass instruments', 'intrumenty blaszane'],
            ['keyboard instruments', 'intrumenty klawiszowe'],
            ['jazz', 'jazz'],
            ['lead singer', 'solista'],
            ['lyrics', 'tekst piosenki'],
            ['melody', 'melodia'],
            ['classical music', 'muzyka klasyczna'],
            ['folk music', 'muzyka ludowa'],
            ['musician', 'muzyk'],
            ['opera', 'opera'],
            ['orchestra', 'orkiestra'],
            ['percussion', 'perkusja'],
            ['pianist', 'pianista'],
            ['play the cello', 'grać na wiolonczeli'],
            ['play the drums', 'grać na perkusji'],
            ['play the electric guitar', 'grać na gitarze elektrycznej'],
            ['play the piano', 'grać na fortepianie'],
            ['play the violin', 'grać na skrzypcach'],
            ['play the trumped', 'grać na trąbce'],
            ['saxophonist', 'saksofonista'],
            ['singer', 'piosenkarz'],
            ['song', 'piosenka'],
            ['strings', 'instrumenty smyczkowe'],
            ['violinist', 'skrzypek'],
           
        ],
        'the_performing_arts' => [
            ['audience', 'widownia'],
            ['audition', 'przesłuchanie'],
            ['ballet', 'balet'],
            ['box office', 'kasa biletowa'],
            ['cheer', 'wiwatować'],
            ['clap', 'klaskać'],
            ['costume', 'kostium'],
            ['dance', 'taniec'],
            ['dancer', 'tancerz'],
            ['play', 'sztuka'],
            ['performance, show', 'przedstawienie'],
            ['performing arts', 'sztuki widowiskowe'],
            ['rehearsal', 'próba'],
            ['scenery', 'dekoracje'],
            ['stage', 'scena, estrada'],
            ['theatre', 'teatr'],
        ],
        'the_media' => [
            ['advertisement', 'reklama'],
            ['article', 'artykuł'],
            ['crossword', 'krzyżówka'],
            ['editor', 'redaktor'],
            ['front page', 'pierwsza strona'],
            ['headline', 'nagłówek'],
            ['horoscope', 'horoskop'],
            ['interview', 'wywiad'],
            ['journalist', 'dziennikarz'],
            ['magazine', 'czasopismo'],
            ['women\'s magazine', 'czasopismo dla kobiet'],
            ['sports magazine', 'czasopismo sportowe'],
            ['international news', 'wiadomości ze świata'],
            ['national news, domestic news', 'wiadomości z kraju'],
            ['newspaper, paper', 'gazeta'],
            ['problem page', 'strona z poradami'],
            ['press', 'prasa'],
            ['publish', 'wydawać, publikować'],
            ['reporter', 'reporter'],
            ['tabloid', 'gazeta popularna, brukowiec'],
            ['channel', 'kanał'],
            ['commercial', 'reklama w radiu lub telewizji'],
            ['live show', 'program na żywo'],
            ['radio', 'radio'],
            ['radio station', 'stacja radiowa'],
            ['remote control', 'pilot'],
            ['cable television', 'telewizja kablowa'],
            ['digital television', 'telewizja cyfrowa'],
            ['satellite television', 'telewizja satelitarna'],
            ['comedy show', 'program komediowy'],
            ['current affairs programme', 'program dotyczący wydarzeń bieżących'],
            ['entertainment programme', 'program rozrywkowy'],
            ['music programme', 'program muzyczny'],
            ['sports programme', 'program sportowy'],
            ['quiz show, game show', 'teleturniej'],
            ['reality TV show', 'reality show'],
            ['sitcom', 'serial komediowy'],
            ['soap opera', 'opera mydlana'],
            ['talk show', 'talk show'],
            ['tv series', 'serial telewizyjny'],
            
        ],

        

    ];

}
