<?php

namespace App\Langs\levels;

use App\Langs\BaseLevel;

/**
 * Created by PhpStorm.
 * User: Roman Pytka
 * Date: 2/28/21
 * Time: 8:23 AM
 */

class Fifth extends BaseLevel
{
    public $title = 'Człowiek';
    public $desc = 'moduł piąty';
    public $slug = 'human';
    public $data = [
        'personal_details' => [
            ['address', 'adres'],
            ['age', 'wiek'],
            ['citizen', 'obywatel'],
            ['citizenship', 'obywatelstwo'],
            ['date of birth', 'data urodzenia'],
            ['delete where applicable', 'niepotrzebne skreślić'],
            ['email address', 'adres e-mailowy'],
            ['female', 'płeć żeńska'],
            ['first name', 'imię'],
            ['hair colour', 'kolor włosów'],
            ['home town', 'miasto zamieszkania'],
            ['job', 'praca'],
            ['male', 'płeć męska'],
            ['man', 'mężczyzna'],
            ['nationality', 'narodowość'],
            ['occupation', 'zawód'],
            ['personal interests', 'zainteresowania'],
            ['physical appearance', 'wygląd zewnętrzny'],
            ['sex', 'płęć'],
            ['surname', 'nazwisko'],
            ['telephone no.', 'numer telefonu'],
            ['women', 'kobieta'],
            ['divorced', 'rozwiedziony'],
            ['martial status', 'stan cywilny'],
            ['married', 'żonaty'],
            ['single', 'nieżonaty'],
            ['widow', 'wdowa'],
            ['widower', 'wdowiec'],

        ],
        'physical_appearance' => [
            ['age', 'wiek'],
            ['elderly', 'w podeszłym wieku'],
            ['in his early twenties', 'trochę ponad 20 lat'],
            ['in his late forties', 'przed 50-tką'],
            ['in his mid thirties', 'około 35 lat'],
            ['middle-age', 'w średnim wieku'],
            ['old', 'stary'],
            ['teenager', 'nastolatek'],
            ['young', 'młody'],
            ['build', 'budowa'],
            ['fat', 'gruby'],
            ['medium-build', 'średniej budowy ciała'],
            ['plump', 'pulchny'],
            ['overweight', 'z nadwagą'],
            ['slim', 'szczupły'],
            ['thin', 'chudy'],
            ['well-build', 'dobrze zbudowany'],
            ['asian', 'azjatycki'],
            ['black', 'czarny'],
            ['skin colour', 'kolor skóry'],
            ['white', 'biały'],
            ['bald', 'łysy'],
            ['beard', 'broda'],
            ['distinguishing features', 'cechy szczególne'],
            ['freckles', 'piegi'],
            ['moustache', 'wąsy'],
            ['scar', 'blizna'],
            ['tatoo', 'tatuaż'],
            ['wrinkles', 'zmarszczki'],
            ['eyes', 'oczy'],
            ['blue eyes', 'niebieskie oczy'],
            ['expressive eyes', 'pełne wyrazu oczy'],
            ['green eyes', 'zielone oczy'],
            ['attractive', 'atrakcyjny'],
            ['beautiful', 'piękny'],
            ['general impression', 'ogólne wrażenie'],
            ['good-looking, attractive', 'atrakcyjny'],
            ['handsome', 'przystojny'],
            ['pretty', 'ładny'],
            ['ugly', 'brzydki'],
            ['unattractive', 'nieatrakcyjny'],
            ['hair', 'włosy'],
            ['blond hair', 'blond włosy'],
            ['curly hair', 'kręcone włosy'],
            ['dark hair', 'ciemne włosy'],
            ['fair hair', 'jasne włosy'],
            ['long hair', 'długie włosy'],
            ['short hair', 'krótkie włosy'],
            ['straight hair', 'proste włosy'],
            ['wavy hair', 'falujące włosy'],
            ['white hair', 'siwe włosy'],
            ['height, increase', 'wzrost'],
            ['medium-height', 'średniego wzrostu'],
            ['tall', 'wysokiego wzrostu'],
            ['short', 'niskiego wzrostu'],

        ],
        'personality' => [
            ['adventurous', 'żądny przygód'],
            ['aggressive', 'agresywny'],
            ['ambitious', 'ambitny'],
            ['bossy', 'dominujący'],
            ['brave', 'dzielny, odważny'],
            ['cheerful', 'radosny, pogodny'],
            ['clever', 'sprytny'],
            ['confident', 'pewny siebie'],
            ['creative', 'twórczy'],
            ['dishonest', 'nieuczciwy'],
            ['friendly', 'przyjazny'],
            ['generous', 'hojny, wspaniałomyślny'],
            ['gentle', 'łagodny, delikatny'],
            ['hard-working', 'pracowity'],
            ['have a sense of humour', 'mieć poczucie humoru'],
            ['honest', 'uczciwy'],
            ['impatient', 'niecierpliwy'],
            ['independent', 'niezależny'],
            ['lazy', 'leniwy'],
            ['lively', 'żywy, żywiołowy'],
            ['loving', 'kochający'],
            ['mean', 'złośliwy'],
            ['stingy, skimpy, miserly', 'skąpy'],
            ['modest', 'skromny'],
            ['open', 'otwarty'],
            ['over-ambitious', 'nadmiernie ambitny'],
            ['patient', 'cierpliwy'],
            ['personality', 'osobowość'],
            ['polite', 'uprzejmy'],
            ['quality', 'cecha'],
            ['quite', 'cichy'],
            ['rude', 'niegrzeczny, źle wychowany'],
            ['sensitive', 'wrażliwy'],
            ['selfish', 'samolubny'],
            ['shy', 'nieśmiały'],
            ['sociable', 'towarzyski'],
            ['stupid', 'głupi'],
            ['talkative', 'rozmowny'],
            ['unambitious', 'bez ambicji'],
            ['unconfident', 'niepewny siebie'],
            ['unfriendly', 'nieprzyjazny'],
            ['height', 'wzrost'],
        ],
        'feelings' => [
            ['admire', 'podziwiać'],
            ['amazed', 'zdumiony'],
            ['angry', 'zły'],
            ['annoyed', 'zirytowany, zły'],
            ['care about sb', 'komuś zależy na kimś'],
            ['dislike', 'nie lubić'],
            ['embarrassed', 'zakłopotany'],
            ['feel ', 'czuć się'],
            ['feel happy', 'czuć się szczęśliwym'],
            ['feel unhappy', 'czuć nieszczęśliwym'],
            ['feel lonely', 'czuć samotnym'],
            ['feeling', 'uczucie'],
            ['frightened', 'przestraszony'],
            ['pleased', 'zadowolony'],
            ['relaxed', 'zrelaksowany'],
            ['shocked', 'zszokowany'],
            ['surprised', 'zdziwiony'],
            ['tired', 'zmęczony'],
            ['upset', 'zaniepokojojny, zdenerwowany'],
            ['worried', 'zmartwiony'],
            ['worry about sth', 'martwić się czymś'],
            ['be excited about sth', 'być czymś podekscytowanym'],
            ['be jealous of sth', 'być o coś zazdrosny'],
            ['be nervous about sth', 'denerwować się czymś'],
            ['feel sorry for sb', 'współczuć komuś'],
            ['avoid', 'unikać'],
            ['be afraid of sth', 'bać się czegoś'],
            ['be terrified of sth', 'panicznie bać się czegoś'],
            ['can\'t stand sth ', 'nie znosić czegoś'],
            ['despise', 'pogardzać'],
            ['dislike', 'nie lubić'],
            ['don\'t mind sth', 'nie mieć nic przeciwko czemuś'],
            ['fear', 'strach'],
            ['feel all right about sth', 'nie mieć z czymś problemu'],
            ['get nervous', 'denerwować się'],
            ['hate', 'nienawidzić'],
            ['stay away from sth', 'trzymać się z dala od czegoś'],
            ['phobia', 'fobia'],
            ['scared', 'przestraszony'],
            ['blame', 'winić'],
            ['follow', 'podążać za'],
            ['take advantage of sb', 'wykorzystywać kogoś'],


        ]

    ];

}
