<?php

namespace App\Langs\levels;

/**
 * Created by PhpStorm.
 * User: Roman Pytka
 * Date: 2/28/21
 * Time: 8:23 AM
 */

class Fourth
{
    public $title = 'Zakupy i Usługi';
    public $slug = 'shopping-and-services';
    public $data = [
        'kinds_of_shops' => [
            ['baker\'s', 'piekarnia'],
            ['bookshop', 'księgarnia'],
            ['butcher\'s', 'sklep mięsny'],
            ['chain store', 'sklep należący do sieci sklepów'],
            ['chemist\'s', 'apteka, drogeria'],
            ['delicatessen', 'delikatesy'],
            ['department store', 'dom towarowy'],
            ['DIY store', 'sklep z artykułami do wykonywania prac w domu, sklep do domowych prac'],
            ['fishmonger\'s', 'sklep rybny'],
            ['florist\'s', 'kwiaciarnia'],
            ['greengrocer\'s', 'sklep owocowno-warzywny'],
            ['grocer\'s', 'sklep spożywczy'],
            ['jewellery shop', 'jubiler'],
            ['market', 'rynek, targ'],
            ['market stall', 'stragan, stoisko'],
            ['newsagent\'s', 'kiosk z gazetami'],
            ['off-licence', 'sklep monopolowy'],
            ['pharmacy', 'apteka'],
            ['clothes shop', 'sklep z ubraniami'],
            ['electrical shop', 'sklep z artykułami elektrycznymi'],
            ['healthy food shop', 'sklep ze zdrową żywnością'],
            ['local shop', 'sklep lokalny'],
            ['shoe shop', 'sklep obuwniczy'],
            ['sports shop', 'sklep z artykułami sportowymi'],
            ['stationery shop', 'sklep z artykułami papierniczymi'],
            ['shoping center', 'centrum handlowe'],
            ['supermarket', 'supermarket'],



        ],
        'services' => [
            ['bank', 'bank'],
            ['car wash', 'myjnia samochodowa'],
            ['dry cleaner\'s', 'pralnia chemiczna'],
            ['estate agent\'s', 'agent nieruchomości'],
            ['hairdresser\'s', 'fryzjer'],
            ['petrol station', 'stacja benzynowa'],
            ['post office', 'poczta'],
            ['service', 'usługa'],
            ['travel agent\'s', 'biuro podróży'],

        ],
        'shopping_and_using_services' => [
            ['bargain', 'okazja'],
            ['search for a bargain', 'data'],
            ['book a holiday', 'rezerwować wakacje'],
            ['buy', 'kupować'],
            ['change', 'reszta'],
            ['cheap', 'tani'],
            ['buy online', 'kupować przez internet'],
            ['buy stamps', 'kupować znaczki pocztowe'],
            ['changing, fitting room', 'przymierzalnia'],
            ['checkout', 'kasa w sklepie'],
            ['close down', 'kończyć działąlność'],
            ['cost', 'kosztować'],
            ['customer', 'klient'],
            ['discount', 'obniżka'],
            ['escalator', 'ruchome schody'],
            ['expensive', 'drogi'],
            ['free', 'za darmo'],
            ['have a haircut', 'ostrzyc się'],
            ['internet shopping', 'zakupy przez internet'],
            ['lift', 'winda'],
            ['open a shop', 'zakładać, otwierać sklep'],
            ['pay by cash', 'płacić gotówką'],
            ['pay by credit card', 'płacić kartą kredytową'],
            ['pay by cheque', 'płacić czekiem'],
            ['price', 'cena'],
            ['queue', 'kolejka, stać w kolejce'],
            ['receipt', 'paragon'],
            ['bill', 'rachunek'],
            ['sale', 'wyprzedaż'],
            ['in the sale', 'w przecenie, na wyprzedaż'],
            ['send flowers', 'wysyłać kwiaty'],
            ['send parcels', 'wysyłać paczki'],
            ['spend money on sth', 'wydawać na coś pieniądze'],
            ['sell', 'sprzedawać'],
            ['shop assistant', 'sprzedawca'],
            ['shopping list', 'lista zakupów'],
            ['special offer', 'promocja, oferta specjalna'],
            ['stall holder', 'właściciel stoiska'],
            ['supermarket trolley', 'wózek na zakupy'],
        ],
        'banking' => [
            ['account number', 'numer konta'],
            ['bank account', 'rachunek bankowy'],
            ['borrow money', 'pożyczać od kogoś pieniądze'],
            ['cash', 'gotówka'],
            ['cash machine', 'bankomat'],
            ['cheque', 'czek'],
            ['credit card', 'karta kredytowa'],
            ['debit card', 'karta debetowa'],
            ['exchange money', 'wymieniać pieniądze'],
            ['exchange rate', 'kurs wymiany waluty'],
            ['fill out the form', 'wypełaniać formularz'],
            ['foreign currency', 'obca waluta'],
            ['lend money', 'pożyczać komuś pieniądze'],
            ['pay in a cheque', 'wpłacać czek do banku'],
            ['pin number', 'numer pin'],
            ['save money', 'oszczędzać pieniądze'],
            ['traveller\'s cheque', 'czek podróżny'],



        ],
        'clothes' => [
            ['boots', 'buty zimowe, buty ciężkie'],
            ['blouse', 'bluzka'],
            ['bra', 'biustonosz'],
            ['cap', 'czapka'],
            ['clothes', 'odzież, ubrania'],
            ['casual clothes', 'codzienna odzież, zwyczajna odzież'],
            ['elegant clothes, smart clothes', 'elegancka odzież'],
            ['fashionable clothes', 'modna odzież'],
            ['coat', 'płaszcz'],
            ['dress', 'sukienka'],
            ['footwear', 'obuwie'],
            ['go with, suit', 'dobrze wyglądać pod względem koloru, dobrze wyglądać pod względem kroju'],
            ['item of clothing', 'część stroju'],
            ['jacket', 'marynarka, kurtka'],
            ['jeans', 'dżinsy'],
            ['jumper', 'sweter, bluza'],
            ['long-sleeved', 'z długim rękawem'],
            ['outfit', 'kostium, ubranie'],
            ['put on', 'wkładać na siebie'],
            ['pyjamas', 'piżama'],
            ['sandal', 'sandał'],
            ['large size', 'duży rozmiar'],
            ['medium size', 'średni rozmiar'],
            ['small size', 'mały rozmiar'],
            ['shirt', 'koszula'],
            ['shoes', 'buty'],
            ['short-sleeved', 'z krótkim rękawem'],
            ['skirt', 'spódnica'],
            ['sleeved', 'rękaw'],
            ['sleeveless', 'bez rękawów'],
            ['slippers', 'kapcie'],
            ['socks', 'skarpetki'],
            ['suit', 'garnitur'],
            ['sweatshirt', 'sweter, bluza'],
            ['take off clothes', 'zdejmować ubranie'],
            ['tie', 'krawat'],
            ['tights', 'rajstopy'],
            ['top', 'bluzka, top'],
            ['trainers', 'buty sportowe, adidasy'],
            ['trousers', 'spodnie'],
            ['try on clothes', 'przymierzać ubranie'],
            ['t-shirt', 'koszulka z krótkim rękawem'],
            ['underwear', 'bielizna'],
            ['wear', 'nosić'],
            ['wear out', 'znosić'],
            ['zip', 'suwak'],
            ['cotton', 'bawełna'],
            ['denim', 'materiał dżinsowy'],
            ['leather', 'skóra'],
            ['linen', 'len'],
            ['material', 'materiał, surowiec'],
            ['wool', 'wełna'],
            ['checked', 'w kratkę'],
            ['dotted', 'w kropki'],
            ['plain', 'gładki, bez wzoru'],
            ['pattern', 'wzór'],
            ['patterned', 'wzorzysty'],
            ['striped', 'w paski'],
            ['accessories', 'dodatki'],
            ['belt', 'pasek'],
            ['bracelet', 'bransoletka'],
            ['earrings', 'kolczyki'],
            ['gloves', 'rękawiczki'],
            ['handbag', 'torebka'],
            ['hat', 'kapelusz'],
            ['jewellery', 'biżuteria'],
            ['necklace', 'naszyjnik'],
            ['ring', 'pierścionek'],
            ['scarf', 'szalik, apaszka'],
            ['sunglasses', 'okulary przeciwsłoneczne'],
            ['watch', 'zegarek'],
        ],
        'foulty_goods' => [
            ['bring sth back', 'zwrócić coś'],
            ['broken', 'zepsuty'],
            ['exchange sth for sth', 'wymieniać coś na coś'],
            ['foulty goods', 'wadliwy towar'],
            ['get money back', 'otrzymać zwrot pieniędzy'],
            ['fit', 'wyglądać dobrze, być w odpowiednim rozmiarze'],
            ['not work', 'nie działa'],
            ['receipt', 'rachunek'],
            ['refund', 'zwrot pieniędzy'],
            ['replacement', 'wymiana'],
            ['scratched', 'porysowany'],
         
        ],

    ];

}
