<?php

namespace App\Langs\levels;

use App\Langs\BaseLevel;

/**
 * Created by PhpStorm.
 * User: Roman Pytka
 * Date: 2/28/21
 * Time: 8:23 AM
 */

class Twentythird extends BaseLevel
{
    public $title = 'IT';
    public $desc = 'moduł dwudziesty trzeci';
    public $slug = 'it-words';
    public $data = [
        'sth' => [
           
            ["algorithm", "algorytm"],
            ["array", "tablica"],
            ["boolean", "logiczny"],
            ["bug", "błąd"],
            ["byte", "bajt"],
            ["cache", "pamięć podręczna"],
            ["class", "klasa"],
            ["compiler", "kompilator"],
            ["database", "baza danych"],
            ["debug", "debugowanie"],
            ["encryption", "szyfrowanie"],
            ["exception", "wyjątek"],
            ["framework", "szkielet"],
            ["function", "funkcja"],
            ["hardware", "sprzęt"],
            ["inheritance", "dziedziczenie"],
            ["interface", "interfejs"],
            ["iteration", "iteracja"],
            ["library", "biblioteka"],
            ["loop", "pętla"],
            ["memory", "pamięć"],
            ["method", "metoda"],
            ["module", "moduł"],
            ["network", "sieć"],
            ["object", "obiekt"],
            ["operator", "operator"],
            ["parameter", "parametr"],
            ["pointer", "wskaźnik"],
            ["protocol", "protokół"],
            ["query", "zapytanie"],
            ["recursion", "rekursja"],
            ["repository", "repozytorium"],
            ["server", "serwer"],
            ["software", "oprogramowanie"],
            ["syntax", "składnia"],
            ["thread", "wątek"],
            ["variable", "zmienna"],
            ["virtual", "wirtualny"],
            ["widget", "widżet"],
            ["workflow", "przepływ pracy"],
            ["access", "dostęp"],
            ["backup", "kopia zapasowa"],
            ["bandwidth", "przepustowość"],
            ["bit", "bit"],
            ["browser", "przeglądarka"],
            ["buffer", "bufor"],
            ["bytecode", "kod bajtowy"],
            ["cloud", "chmura"],
            ["cluster", "klaster"],
            ["command", "komenda"],
            ["compression", "kompresja"],
            ["connectivity", "łączność"],
            ["cookie", "ciasteczko"],
            ["data", "dane"],
            ["default", "domyślny"],
            ["dependency", "zależność"],
            ["deployment", "wdrożenie"],
            ["directory", "katalog"],
            ["disk", "dysk"],
            ["domain", "domena"],
            ["firewall", "zapora sieciowa"],
            ["gateway", "brama"],
            ["hosting", "hosting"],
            ["index", "indeks"],
            ["input", "wejście"],
            ["instance", "instancja"],
            ["integration", "integracja"],
            ["internet", "internet"],
            ["IP address", "adres IP"],
            ["key", "klucz"],
            ["latency", "opóźnienie"],
            ["license", "licencja"],
            ["load", "obciążenie"],
            ["log", "log"],
            ["middleware", "oprogramowanie pośredniczące"],
            ["node", "węzeł"],
            ["packet", "pakiet"],
            ["partition", "partycja"],
            ["path", "ścieżka"],
            ["ping", "ping"],
            ["port", "port"],
            ["proxy", "serwer proxy"],
            ["RAM", "pamięć RAM"],
            ["recursion", "rekursja"],
            ["repository", "repozytorium"],
            ["request", "żądanie"],
            ["response", "odpowiedź"],
            ["restore", "przywrócenie"],
            ["root", "korzeń"],
            ["routing", "trasowanie"],
            ["runtime", "czas wykonania"],
            ["scalability", "skalowalność"],
            ["script", "skrypt"],
            ["security", "bezpieczeństwo"],
            ["session", "sesja"],
            ["shell", "powłoka"],
            ["snapshot", "migawka"],
            ["socket", "gniazdo"],
            ["source", "źródło"],
            ["stack", "stos"],
            ["storage", "magazynowanie"],
            ["stream", "strumień"],
            ["subnet", "podsiec"],
            ["syntax", "składnia"],
            ["system", "system"],
            ["table", "tabela"],
            ["thread", "wątek"],
            ["token", "token"],
            ["traffic", "ruch"],
            ["transaction", "transakcja"],
            ["trigger", "wyzwalacz"],
            ["tunnel", "tunel"],
            ["upload", "przesyłanie"],
            ["URL", "adres URL"],
            ["user", "użytkownik"],
            ["utility", "narzędzie"],
            ["version", "wersja"],
            ["virtual machine", "maszyna wirtualna"],
            ["virtualization", "wirtualizacja"],
            ["virus", "wirus"],
            ["web", "sieć"],
            ["web server", "serwer internetowy"],
            ["website", "strona internetowa"],
            ["whitelist", "lista dozwolonych"],
            ["widget", "widżet"],
            ["wireless", "bezprzewodowy"],
            ["workflow", "przepływ pracy"],
            ["API", "interfejs programistyczny aplikacji"],
            ["authentication", "uwierzytelnianie"],
            ["authorization", "autoryzacja"],
            ["bandwidth", "przepustowość"],
            ["cache", "pamięć podręczna"],
            ["callback", "wywołanie zwrotne"],
            ["certificate", "certyfikat"],
            ["cipher", "szyfr"],
            ["client", "klient"],
            ["command line", "linia komend"],
            ["concatenation", "łączenie"],
            ["concurrency", "współbieżność"],
            ["configuration", "konfiguracja"],
            ["container", "kontener"],
            ["cryptography", "kryptografia"],
            ["data structure", "struktura danych"],
            ["debugging", "debugowanie"],
            ["decryption", "odszyfrowanie"],
            ["DNS", "system nazw domen"],
            ["endpoint", "punkt końcowy"],
            ["entity", "jednostka"],
            ["firewall", "zapora ogniowa"],
            ["frontend", "frontend"],
            ["gateway", "brama"],
            ["hash", "skrótu"],
            ["HTTP", "protokół przesyłania hiperłączy"],
            ["HTTPS", "protokół przesyłania hiperłączy z szyfrowaniem"],
            ["interface", "interfejs"],
            ["IP", "protokół internetowy"],
            ["JSON", "notacja obiektowa JavaScript"],
            ["latency", "opóźnienie"],
            ["load balancing", "równoważenie obciążenia"],
            ["loopback", "powrót pętli"],
            ["malware", "złośliwe oprogramowanie"],
            ["metadata", "metadane"],
            ["microservices", "mikrousługi"],
            ["monitoring", "monitorowanie"],
            ["node", "węzeł"],
            ["object-oriented", "zorientowany obiektowo"],
            ["output", "wyjście"],
            ["overload", "przeciążenie"],
            ["parser", "parser"],
            ["payload", "ładunek"],
            ["ping", "ping"],
            ["pipeline", "potok"],
            ["port", "port"],
            ["queue", "kolejka"],
            ["rate limiting", "ograniczenie prędkości"],
            ["recursion", "rekursja"],
            ["request", "żądanie"],
            ["reverse proxy", "odwrócony serwer proxy"],
            ["router", "router"],
            ["runtime", "czas wykonywania"],
            ["scheduler", "planista"],
            ["serialization", "serializacja"],
            ["serverless", "bezserwerowy"],
            ["singleton", "singleton"],
            ["socket", "gniazdo"],
            ["SSH", "bezpieczna powłoka"],
            ["SSL", "warstwa zabezpieczeń gniazd"],
            ["stateless", "bezdostępny"],
            ["storage", "przechowywanie"],
            ["stream", "strumień"],
            ["subnet", "podsiec"],
            ["synchronous", "synchroniczny"],
            ["system", "system"],
            ["token", "token"],
            ["transaction", "transakcja"],
            ["tunnel", "tunel"],
            ["unit testing", "testowanie jednostkowe"],
            ["validation", "walidacja"],
            ["version control", "kontrola wersji"],
            ["virtualization", "wirtualizacja"],
            ["websocket", "gniazdo sieciowe"],
            ["workflow", "przepływ pracy"],
            ["XML", "rozszerzalny język znaczników"],
            ["YAML", "jeszcze inny język znaczników"],
            ["zero-day", "zerowy dzień"],
            ['11111', '111111'],
        ],
       

    

    ];

}
